USE Venture_Market

INSERT Users(ID,Username,Email,Password,FName,LName) VALUES
(1,N'ColinCornish',	N'colin.cornish@gmail.com', N'951357', N'Colin', N'Cornish'),
(2,N'VirginiaBond',	N'virginia.bond@gmail.com', N'852654', N'Virginia', N'Bond'),
(3,N'SallyClarkson', N'sally.clarkson@gmail.com', N'753951', N'Sally', N'Clarkson'),
(4,N'LeonardDickens', N'leonard.dickens@gmail.com', N'987321', N'Leonard', N'Dickens'),
(5,N'ThomasMay', N'thomas.may@gmail.com', N'456951', N'Thomas', N'May'),
(6,N'DorothyInce', N'dorothy.ince@gmail.com', N'963741', N'Dorothy', N'Ince'),
(7,N'DonnaMorrison', N'donna.morrison@gmail.com', N'852753', N'Donna', N'Morrison'),
(8,N'JonathanHughes', N'jonathan.hughes@gmail.com', N'741963', N'Jonathan', N'Hughes'),
(9,N'ChloeCampbell', N'chloe.campbell@gmail.com', N'8426842', N'Chloe', N'Campbell'),
(10,N'MichelleLee', N'michelle.lee@gmail.com', N'957135', N'Michelle', N'Lee'),
(11,N'TrevorGill', N'trevor.gill@gmail.com', N'397182', N'Trevor', N'Gill'),
(12,N'VictoriaInce', N'victoria.ince@gmail.com', N'791346', N'Victoria', N'Ince'),
(13,N'DavidJones', N'david.jones@gmail.com', N'957535', N'David', N'Jones'),
(14,N'EdwardReid', N'edward.reid@gmail.com', N'759614', N'Edward', N'Reid'),
(15,N'DonnaBuckland', N'donna.buckland@gmail.com', N'852545', N'Donna', N'Buckland'),
(16,N'JackAvery', N'jack.avery@gmail.com', N'782398', N'Jack', N'Avery'),
(17,N'JoeCornish', N'joe.cornish@gmail.com', N'983278', N'Joe', N'Cornish'),
(18,N'JaneWright', N'jane.wright@gmail.com', N'129832', N'Jane', N'Wright'),
(19,N'SallyNewman', N'sally.newman@gmail.com', N'45657595', N'Sally', N'Newman'),
(20,N'FionaChapman', N'fiona.chapman@gmail.com', N'842695', N'Fiona', N'Chapman'),
(21,N'GabrielleDavies', N'gabrielle.davies@gmail.com', N'951357', N'Gabrielle', N'Davies'),
(22,N'ElizabethKelly',	N'elizabeth.kelly@gmail.com', N'852654', N'Elizabeth', N'Kelly'),
(23,N'JoannePiper', N'joanne.piper', N'753951', N'Joanne', N'Piper'),
(24,N'AustinPeters', N'austin.peters@gmail.com', N'987321', N'Austin', N'Peters'),
(25,N'AmyOgden', N'amy.ogden@gmail.com', N'456951', N'Amy', N'Ogden'),
(26,N'MichaelCampbell', N'michael.campbell@gmail.com', N'963741', N'Michael', N'Campbell'),
(27,N'AndreaDavidson', N'andrea.davidson@gmail.com', N'852753', N'Andrea', N'Davidson'),
(28,N'BenjaminMitchell', N'benjamin.mitchell@gmail.com', N'741963', N'Benjamin', N'Mitchell'),
(29,N'DanParsons', N'dan.parsons@gmail.com', N'8426842', N'Dan', N'Parsons'),
(30,N'ThomasAlsop', N'thomas.alsop@gmail.com', N'957135', N'Thomas', N'Alsop'),
(31,N'JohnArnold', N'john.arnold@gmail.com', N'397182', N'John', N'Arnold'),
(32,N'NatalieNolan', N'natalie.nolan@gmail.com', N'791346', N'Natalie', N'Nolan'),
(33,N'ConnorBlack', N'connor.black@gmail.com', N'957535', N'Connor', N'Black'),
(34,N'KarenBerry', N'karen.berry@gmail.com', N'759614', N'Karen', N'Berry'),
(35,N'MollyWright', N'molly.wright@gmail.com', N'852545', N'Molly', N'Wright'),
(36,N'DianePaige', N'diane.paige@gmail.com', N'782398', N'Diane', N'Paige'),
(37,N'JacobVaughan', N'jacob.vaughan@gmail.com', N'983278', N'Jacob', N'Vaughan'),
(38,N'AlisonMetcalfe', N'alison.metcalfe@gmail.com', N'129832', N'Alison', N'Metcalfe'),
(39,N'RyanInce', N'ryan.ince@gmail.com', N'45657595', N'Ryan', N'Ince'),
(40,N'WandaMorrison', N'wanda.morrison@gmail.com', N'842695', N'Wanda', N'Morrison')
SET IDENTITY_INSERT Users OFF